MAX_DAILY_LOAD_NO = 3
MAX_DAILY_LOAD_AMOUNT = 5000
MAX_WEEKLY_LOAD_AMOUNT = 20000
UTC_DATE_TIME_FORMAT = "%Y-%m-%dT%H:%M:%SZ"
DAILY_NO_LOAD_LIMIT_ERROR = "Can not add more than 3 records for date %s"
DAILY_LOAD_AMOUNT_LIMIT_ERROR = "Daily Load Amount exceed"
WEEKLY_LOAD_AMOUNT_LIMIT_ERROR = "Weekly Load Amount exceed"
